spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product_service_route
              uri: http://localhost:8081
              predicates:
                - Path=/api/**
              filters:
                - TokenCheckGatewayFilter
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23ligV0vfMlsEmQNyi
            client-secret: 761c2407ceaab49a0aca42507c2e1adb7ed47e6d
            scope:
              - read:user
              - user:email
        provider:
          github:
            user-name-attribute: login

server:
  port: 8080
