spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product_service_route
              uri: http://localhost:8081
              predicates:
                - Path=/api/**
              filters:
                - TokenCheckGatewayFilter
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23ligV0vfMlsEmQNyi
            client-secret: d2e51ae2a6c41b081b5cb7bbf0b1790f857123ed
            scope:
              - read:user
              - user:email
        provider:
          github:
            user-name-attribute: login

server:
  port: 8080
